@startuml
start

:'学生在线发起借阅申请';
:'系统验证借阅条件';

if (验证是否成功?) then (否)
    :'系统提示失败信息';
    --> '学生重新发起借阅申请';
    -> '学生在线发起借阅申请';
else (是)
    :'图书管理员审核借阅请求';

    if (管理员是否批准?) then (否)
        :'管理员查看申请详情';
        --> '学生在线发起借阅申请';
        -> '学生在线发起借阅申请';
    else (是)
        :'系统生成借阅记录';
        :'学生查看我的借阅信息';
        if (学生是否看到新借阅信息?) then (否)
            :'管理员检查借阅流程';
            -> '图书管理员审核借阅请求';
        else (是)
            :'借阅成功';
        endif
    endif
endif

stop
@enduml
